SELECT * FROM [TABELA DE CLIENTES]

SELECT * FROM [ITENS NOTAS FISCAIS]

SELECT * FROM [TABELA DE PRODUTOS]

SELECT * FROM [NOTAS FISCAIS] 

-- QUANTO CADA CLIENTE COMPROU NO MÊS

(SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.[DATA],120),1,7) AS [ANO-MÊS], SUM(INF.QUANTIDADE) AS [QTDE/MÊS] FROM [NOTAS FISCAIS] NF 
INNER JOIN [ITENS NOTAS FISCAIS] INF ON NF.NUMERO = INF.NUMERO 
GROUP BY NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.[DATA],120),1,7)) CQ

(SELECT  TC.NOME, TC.[VOLUME DE COMPRA], TC.CPF, CQ.[ANO-MÊS], CQ.[QTDE/MÊS] FROM [TABELA DE CLIENTES] TC
INNER JOIN (SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.[DATA],120),1,7) AS [ANO-MÊS], SUM(INF.QUANTIDADE) AS [QTDE/MÊS] FROM [NOTAS FISCAIS] NF 
INNER JOIN [ITENS NOTAS FISCAIS] INF ON NF.NUMERO = INF.NUMERO 
GROUP BY NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.[DATA],120),1,7)) CQ
ON TC.CPF = CQ.CPF) AUX1

SELECT AUX1.NOME, AUX1.[ANO-MÊS], AUX1.[QTDE/MÊS], (-AUX1.[QTDE/MÊS] + AUX1.[VOLUME DE COMPRA]) AS DIFERENÇA,
CASE WHEN AUX1.[QTDE/MÊS] <= AUX1.[VOLUME DE COMPRA] THEN 'VENDA VÁLIDA' ELSE 'VENDA INVÁLIDA'
END AS [STATUS VENDA]
FROM (SELECT  TC.NOME, TC.[VOLUME DE COMPRA], TC.CPF, CQ.[ANO-MÊS], CQ.[QTDE/MÊS] FROM [TABELA DE CLIENTES] TC
INNER JOIN (SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.[DATA],120),1,7) AS [ANO-MÊS], SUM(INF.QUANTIDADE) AS [QTDE/MÊS] FROM [NOTAS FISCAIS] NF 
INNER JOIN [ITENS NOTAS FISCAIS] INF ON NF.NUMERO = INF.NUMERO 
GROUP BY NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.[DATA],120),1,7)) CQ
ON TC.CPF = CQ.CPF) AUX1
ORDER BY AUX1.NOME, AUX1. [ANO-MÊS]