SELECT * FROM [TABELA DE CLIENTES]

SELECT * FROM [TABELA DE VENDEDORES]

SELECT * FROM [TABELA DE PRODUTOS]

SELECT * FROM [ITENS NOTAS FISCAIS]

SELECT * FROM [NOTAS FISCAIS]

-- FATURAMENTO EM 2016 POR SABOR 

(SELECT INF.[NUMERO], INF.[CODIGO DO PRODUTO], INF.[QUANTIDADE], INF.[PREÇO], NF.[DATA] FROM [ITENS NOTAS FISCAIS] INF
INNER JOIN [NOTAS FISCAIS] NF
ON INF.[NUMERO] = NF.[NUMERO] WHERE YEAR([DATA]) = 2016) AUX1

SELECT TP.SABOR, SUBSTRING(CONVERT(VARCHAR,AUX1.[DATA]),1,4) AS ANO, AUX1.[QUANTIDADE], AUX1.[PREÇO] 
FROM [TABELA DE PRODUTOS] TP INNER JOIN (SELECT INF.[NUMERO], INF.[CODIGO DO PRODUTO], INF.[QUANTIDADE], INF.[PREÇO], NF.[DATA] FROM [ITENS NOTAS FISCAIS] INF
INNER JOIN [NOTAS FISCAIS] NF
ON INF.[NUMERO] = NF.[NUMERO] WHERE YEAR([DATA]) = 2016) AUX1
ON TP.[CODIGO DO PRODUTO] = AUX1.[CODIGO DO PRODUTO]


(SELECT AUX2.SABOR, AUX2.ANO, SUM((QUANTIDADE*PREÇO)) AS FATURAMENTO FROM (SELECT TP.SABOR, SUBSTRING(CONVERT(VARCHAR,AUX1.[DATA]),1,4) AS ANO, AUX1.[QUANTIDADE], AUX1.[PREÇO] 
FROM [TABELA DE PRODUTOS] TP INNER JOIN (SELECT INF.[NUMERO], INF.[CODIGO DO PRODUTO], INF.[QUANTIDADE], INF.[PREÇO], NF.[DATA] FROM [ITENS NOTAS FISCAIS] INF
INNER JOIN [NOTAS FISCAIS] NF
ON INF.[NUMERO] = NF.[NUMERO] WHERE YEAR([DATA]) = 2015) AUX1
ON TP.[CODIGO DO PRODUTO] = AUX1.[CODIGO DO PRODUTO]) AUX2 GROUP BY SABOR, ANO) AUX3



SELECT SUM(AUX3.FATURAMENTO) FROM (SELECT AUX2.SABOR, AUX2.ANO, SUM((QUANTIDADE*PREÇO)) AS FATURAMENTO FROM (SELECT TP.SABOR, SUBSTRING(CONVERT(VARCHAR,AUX1.[DATA]),1,4) AS ANO, AUX1.[QUANTIDADE], AUX1.[PREÇO] 
FROM [TABELA DE PRODUTOS] TP INNER JOIN (SELECT INF.[NUMERO], INF.[CODIGO DO PRODUTO], INF.[QUANTIDADE], INF.[PREÇO], NF.[DATA] FROM [ITENS NOTAS FISCAIS] INF
INNER JOIN [NOTAS FISCAIS] NF
ON INF.[NUMERO] = NF.[NUMERO] WHERE YEAR([DATA]) = 2016) AUX1
ON TP.[CODIGO DO PRODUTO] = AUX1.[CODIGO DO PRODUTO]) AUX2 GROUP BY SABOR, ANO
) AUX3


-- FATURAMENTO TOTAL 2016 - 42362118,1877249

SELECT AUX2.SABOR, AUX2.ANO, 
CONVERT(DECIMAL(15,2),SUM((QUANTIDADE*PREÇO)),2) AS [FATURAMENTO (R$)] ,
CONVERT(VARCHAR, CONVERT(DECIMAL(15,2),(SUM((QUANTIDADE*PREÇO))/42362118.1877249)*100)) + ' %' AS PARTICIPAÇÃO 
FROM (SELECT TP.SABOR, SUBSTRING(CONVERT(VARCHAR,AUX1.[DATA]),1,4) AS ANO, AUX1.[QUANTIDADE], AUX1.[PREÇO] 
FROM [TABELA DE PRODUTOS] TP INNER JOIN (SELECT INF.[NUMERO], INF.[CODIGO DO PRODUTO], INF.[QUANTIDADE], INF.[PREÇO], NF.[DATA] FROM [ITENS NOTAS FISCAIS] INF
INNER JOIN [NOTAS FISCAIS] NF
ON INF.[NUMERO] = NF.[NUMERO] WHERE YEAR([DATA]) = 2016) AUX1
ON TP.[CODIGO DO PRODUTO] = AUX1.[CODIGO DO PRODUTO]) AUX2 GROUP BY SABOR, ANO
ORDER BY [FATURAMENTO (R$)] DESC