SELECT * FROM [TABELA DE PRODUTOS]
WHERE [SABOR] = 'LIMÃO'


UPDATE [TABELA DE PRODUTOS] SET [PRECO DE LISTA] = 1.1 * [PRECO DE LISTA] WHERE [SABOR] = 'Limão'

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [SABOR] = 'LIMÃO'

SELECT * FROM [TABELA DE CLIENTES] WHERE DAY([DATA DE NASCIMENTO]) > 15

SELECT * FROM [TABELA DE CLIENTES] WHERE [CIDADE] = 'RIO DE JANEIRO' AND [IDADE] > 18



SELECT * FROM [TABELA DE CLIENTES] WHERE [CIDADE] = 'RIO DE JANEIRO' OR [BAIRRO] = 'TIJUCA'

